- name: Create a logstash container
  docker_container:
    name: logstash
    image: logstash:7.5.1
    networks:
    - name: "elk"
    ports:
    - "5000:5000"
    - "9600:9600"
    volumes:
    - ./roles/logstash/templates/logstash.yml:/usr/share/elasticsearch/config/logstash.yml
