- name: Create an elastic container
  docker_container:
    name: elasticsearch
    image: elasticsearch:7.5.1
    env:
        discovery.type: "single-node"
    networks:
    - name: "elk"
    ports:
    - "9200:9200"
    - "9300:9300"

- name: Create a kibana container
  docker_container:
    name: kibana
    image: kibana:7.5.1
    networks:
    - name: "elk"
    ports:
    - "5601:5601"

- name: Create a logstash container
  docker_container:
    name: logstash
    image: logstash:7.5.1
    networks:
    - name: "elk"
    ports:
    - "5000:5000"
    - "9600:9600"
